- hosts: localhost
  tasks: 
  - name: install git
    become: yes 
    become_method: sudo
    yum: name=git state=latest 
  - name: clone petclinic
    git: 
      repo: https://github.com/shsimkin/spring-petclinic 
      dest: ~/petclinic 
      clone: yes
      update: no 
  - name: clone ciscocd
    git:
      repo: https://github.com/shsimkin/ciscocd 
      dest: ~/ciscocd
      clone: yes
      update: no 
  - name: create downloads directory
    file: 
      path: ~/downloads
      state: directory
  - name: download Maven
    get_url: 
      url: http://www-us.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
      dest: ~/downloads/apache-maven-3.3.9-bin.tar.gz 
  - name: create maven directory
    file: 
      path: ~/maven
      state: directory
  - name: unzip maven archive into Maven directory
    unarchive: 
      src: ~/downloads/apache-maven-3.3.9-bin.tar.gz 
      dest: ~/maven
